undefinedus/backend

.github/workflows/deploy.yml

- echo 를 활용하여 완료된 스크립트 확인 할 수 있도록 업데이트

fix(ci/cd): deploy.yml 에러 수정

---

src/main/java/com/undefinedus/backend/config/MailConfig.java
src/main/java/com/undefinedus/backend/service/EmailService.java

- application.yml 에서 값을 불러오는 코드 업데이트

fix(mail): mail관련 코드 업데이트

---

src/main/java/com/undefinedus/backend/config/CustomSecurityConfig.java
src/main/java/com/undefinedus/backend/controller/MemberController.java
src/main/java/com/undefinedus/backend/security/filter/JWTCheckFilter.java

- CustomSecurityConfig의 코드 업데이트

fix: 무한 로딩 에러 업데이트

---

src/main/java/com/undefinedus/backend/config/InitialDataConfig.java
src/main/java/com/undefinedus/backend/domain/entity/AladinBook.java
src/main/java/com/undefinedus/backend/domain/entity/MyBook.java
src/main/java/com/undefinedus/backend/dto/request/book/AladinBookRequestDTO.java
src/main/java/com/undefinedus/backend/dto/response/aladinAPI/AladinApiDTOList.java
src/main/java/com/undefinedus/backend/dto/response/aladinAPI/AladinApiResponseDTO.java
src/main/java/com/undefinedus/backend/dto/response/aladinAPI/SubInfoDTO.java
src/main/java/com/undefinedus/backend/repository/MemberRepository.java
src/main/java/com/undefinedus/backend/service/MyBookServiceImpl.java

알라딘 도서 api에 맞는 형태로 코드 업데이트
- 바뀐 entity의 내용에 따라 영향을 받는 다른 코드들 업데이트
- dto 추가 및 필요한 필드만 가져오도록 업데이트

fix(aladinBook): 알라딘 도서 api에 맞게 업데이트

---

.github/workflows/deploy.yml

fix(cicd): 코드 업데이트

---

src/main/java/com/undefinedus/backend/domain/entity/BaseEntity.java
src/main/java/com/undefinedus/backend/domain/entity/Member.java
src/main/java/com/undefinedus/backend/domain/entity/MyBook.java

- member 엔티티 칭호 추가, version 1 은 기본 값만 사용
- 각 entity에 setter 추가

fix(entity): 각 엔티티 필드 값 추가

---

src/main/java/com/undefinedus/backend/controller/AladinAPIController.java
src/main/java/com/undefinedus/backend/controller/ChatGPTController.java
src/main/java/com/undefinedus/backend/dto/response/aladinAPI/AladinApiResponseDTO.java
src/main/java/com/undefinedus/backend/exception/aladinBook/AladinBookNotFoundException.java
src/main/java/com/undefinedus/backend/service/AladinBookServiceImpl.java
src/main/java/com/undefinedus/backend/service/ChatGPTService.java
src/main/java/com/undefinedus/backend/service/ChatGPTServiceImpl.java
src/main/resources/promptTemplates/questionDiscussionPromptTemplate.st
src/main/resources/promptTemplates/testPromptTemplate.st

- aladinApi 수정 controller에서 memberId 받는것 수정
service에서 출려되는 정보 중 bestSellerRank 추가
- ChatGPT 수정 연결 확인 테스트용 명령프롬프트 작성(백엔드에서 주는 isbn13을 그대로 gpt가 다시 준다.) service에서 테스트용 명령프롬프트 연결

fix(aladin, ChatGPT): 코드 수정

---

src/main/java/com/undefinedus/backend/domain/entity/AladinBook.java
src/main/java/com/undefinedus/backend/domain/entity/MyBook.java
src/main/java/com/undefinedus/backend/dto/response/aladinAPI/AladinApiResponseDTO.java
src/main/java/com/undefinedus/backend/service/AladinBookServiceImpl.java

- aladinApi 수정 카테고리를 출력할 때 id(숫자)값이었으나 글자로 변경

fix(aladinApi): 코드 수정

---

src/main/java/com/undefinedus/backend/service/AladinBookServiceImpl.java

- aladinApi 수정 카테고리를 출력할 때 id(숫자)값이었으나 글자로 변경

fix(aladinApi): 코드 추가 수정

---

src/main/java/com/undefinedus/backend/dto/response/aladinAPI/SubInfoDTO.java

- aladinApi 떄 필요한 SubInfoDTO 수정 bestSellerRank 추가

fix(aladinApi): DTO 수정

---

src/test/java/com/undefinedus/backend/service/MyBookServiceImplTest.java

- setId -> changeId 로 변경
- 모든 테스트 통과 확인

fix(test): 테스트 코드 업데이트

---

src/main/java/com/undefinedus/backend/domain/entity/AladinBook.java
src/main/java/com/undefinedus/backend/dto/response/aladinAPI/AladinApiResponseDTO.java
src/main/java/com/undefinedus/backend/dto/response/aladinAPI/AladinBookForGPTResponseDTO.java
src/test/java/com/undefinedus/backend/repository/AladinBookRepositoryTest.java
src/test/java/com/undefinedus/backend/repository/CalendarStampRepositoryTest.java
src/test/java/com/undefinedus/backend/repository/MyBookRepositoryTest.java
src/test/java/com/undefinedus/backend/repository/MyBookmarkRepositoryTest.java

- aladin엔티티, DTO에 fullDescription2 필드 추가 GPT에게 토론 정보를 넘겨 줄때 기존에 가지고 있던 fullDescription만으로는 GPT가 토론의 주제인 책에 대한 정보 전달이 부족하다 판단되어 좀더 긴 설명을 가지고 있는 fullDescription2를 추가 함.

fix(aladin): 엔티티, DTO에 필드 값 추가

---

src/main/java/com/undefinedus/backend/controller/SocialLoginController.java
src/main/java/com/undefinedus/backend/repository/MemberRepository.java
src/main/java/com/undefinedus/backend/service/MemberServiceImpl.java

fix(socialLogin): 카카오 소셜 로그인 코드 업데이트

---

src/main/java/com/undefinedus/backend/controller/DiscussionCommentController.java
src/main/java/com/undefinedus/backend/dto/response/discussionComment/DiscussionCommentResponseDTO.java
src/main/java/com/undefinedus/backend/repository/DiscussionCommentRepository.java
src/main/java/com/undefinedus/backend/service/DiscussionCommentService.java
src/main/java/com/undefinedus/backend/service/DiscussionCommentServiceImpl.java
src/test/java/com/undefinedus/backend/repository/DiscussionCommentRepositoryTest.java
src/test/java/com/undefinedus/backend/service/DiscussionCommentServiceImplTest.java
src/test/resources/application.yml

-discussionComment 베스트 3 댓글 기능 추가
정렬 순서 댓글, 답글 중 좋아요 많은 순이고 만약 좋아요 수가 동일 하다면 싫어요 작은 순, 만약 좋아요, 싫어요 수가 동일 하다면 댓글을 만든 순서로 설정

feat(discussionComment): 베스트 3 댓글 기능 추가

---

src/main/java/com/undefinedus/backend/controller/StatisticsController.java
src/main/java/com/undefinedus/backend/dto/response/statistics/StatisticsCategoryBookCountResponseDTO.java
src/main/java/com/undefinedus/backend/dto/response/statistics/StatisticsMonthBookAverageByYearResponseDTO.java
src/main/java/com/undefinedus/backend/dto/response/statistics/StatisticsMonthBookByYearResponseDTO.java
src/main/java/com/undefinedus/backend/dto/response/statistics/StatisticsResponseDTO.java
src/main/java/com/undefinedus/backend/dto/response/statistics/StatisticsTotalPageByYearResponseDTO.java
src/main/java/com/undefinedus/backend/dto/response/statistics/StatisticsYearBookResponseDTO.java
src/main/java/com/undefinedus/backend/dto/response/statistics/StatisticsYearResponseDTO.java
src/main/java/com/undefinedus/backend/dto/response/statistics/StatisticsYearsBookInfoResponseDTO.java
src/main/java/com/undefinedus/backend/repository/MyBookRepository.java
src/main/java/com/undefinedus/backend/repository/queryDSL/MyBookRepositoryCustom.java
src/main/java/com/undefinedus/backend/repository/queryDSL/MyBookRepositoryCustomImpl.java
src/main/java/com/undefinedus/backend/scheduler/config/QuartzConfig.java
src/main/java/com/undefinedus/backend/service/StatisticsService.java
src/main/java/com/undefinedus/backend/service/StatisticsServiceImpl.java
src/test/java/com/undefinedus/backend/repository/MyBookRepositoryTest.java
src/test/java/com/undefinedus/backend/service/StatisticsServiceImplTest.java

- 통계 중 카테고리 별, 연_월 별 통계 구현 설정(마이페이지)의 달력 기능 이외의 통계 부분 기능 구현 완료

feat(Statistics): 설정의 통계 부분 기능 구현

---

src/main/java/com/undefinedus/backend/controller/StatisticsController.java
src/main/java/com/undefinedus/backend/dto/response/statistics/StatisticsCategoryResponseDTO.java
src/main/java/com/undefinedus/backend/service/StatisticsService.java
src/main/java/com/undefinedus/backend/service/StatisticsServiceImpl.java
src/test/java/com/undefinedus/backend/service/StatisticsServiceImplTest.java

- 카테고리 별 통계 용 DTO 추가 totoal book count 기능을 추가하여 카테고리 검색 시 유저가 다 읽은 책의 모든 권 수를 확인 하는 기능 추가

fix(Statistics): 설정의 통계 부분 기능 및 DTO 추가

---

src/main/java/com/undefinedus/backend/repository/queryDSL/MemberRepositoryCustomImpl.java

fix(social): 소셜 멤버 검색시 관리자 제외 기능 업데이트

---

src/main/java/com/undefinedus/backend/config/InitialDataConfig.java
src/main/java/com/undefinedus/backend/controller/AladinAPIController.java
src/main/java/com/undefinedus/backend/controller/ChatGPTController.java
src/main/java/com/undefinedus/backend/controller/DiscussionCommentController.java
src/main/java/com/undefinedus/backend/controller/DiscussionController.java
src/main/java/com/undefinedus/backend/controller/StatisticsController.java
src/main/java/com/undefinedus/backend/domain/entity/Member.java
src/main/java/com/undefinedus/backend/dto/response/statistics/StatisticsCategoryByYearResponseDTO.java
src/main/java/com/undefinedus/backend/repository/MemberRepository.java
src/main/java/com/undefinedus/backend/repository/MyBookRepository.java
src/main/java/com/undefinedus/backend/repository/MyBookmarkRepository.java
src/main/java/com/undefinedus/backend/repository/queryDSL/MemberRepositoryCustom.java
src/main/java/com/undefinedus/backend/repository/queryDSL/MemberRepositoryCustomImpl.java
src/main/java/com/undefinedus/backend/scheduler/JobRestorer.java
src/main/java/com/undefinedus/backend/service/MemberServiceImpl.java
src/main/java/com/undefinedus/backend/service/StatisticsService.java
src/main/java/com/undefinedus/backend/service/StatisticsServiceImpl.java
src/test/java/com/undefinedus/backend/repository/MemberRepositoryTest.java
src/test/java/com/undefinedus/backend/repository/MyBookRepositoryTest.java
src/test/java/com/undefinedus/backend/service/StatisticsServiceImplTest.java

- 다 읽은 책 연도를 그룹하여 카테고리 별 카운트
- 각 컨트롤러 메서드에 무슨 기능의 메서드인지 설명 주석 추가

fix(Statistics, Discussion): 연도 별의 카테고리 별 다 읽은 책 카운트, 컨트롤러에 주석 추가

---

src/main/java/com/undefinedus/backend/dto/response/discussion/DiscussionListResponseDTO.java
src/main/java/com/undefinedus/backend/service/DiscussionServiceImpl.java
src/test/java/com/undefinedus/backend/service/DiscussionServiceImplTest.java

- 토론 목록 토론 시작시간, 끝나는 시간 구현 완료 토론 시작시간과 시작시간에서 하루를 더한 시간으로 끝나는 시간 설정 및 목록 에서 출력 됨.

fix(Discussion): 토론 목록에서 토론 시작시간, 끝나는 시간 출력 구현

---

build.gradle
src/main/java/com/undefinedus/backend/config/AiConfig.java
src/main/java/com/undefinedus/backend/controller/AiController.java
src/main/java/com/undefinedus/backend/controller/Kakao.java
src/main/java/com/undefinedus/backend/controller/SocialLoginController.java
src/main/java/com/undefinedus/backend/domain/entity/Member.java
src/main/java/com/undefinedus/backend/repository/queryDSL/MemberRepositoryCustomImpl.java
src/main/java/com/undefinedus/backend/scheduler/KakaoTalkSender.java
src/main/java/com/undefinedus/backend/scheduler/config/QuartzConfig.java
src/main/java/com/undefinedus/backend/scheduler/job/Analyzing.java
src/main/java/com/undefinedus/backend/scheduler/job/Completed.java
src/main/java/com/undefinedus/backend/scheduler/job/InProgress.java
src/main/java/com/undefinedus/backend/scheduler/job/KakaoTalkJob.java
src/main/java/com/undefinedus/backend/service/AiService.java
src/main/java/com/undefinedus/backend/service/AiServiceImpl.java
src/main/java/com/undefinedus/backend/service/KakaoMessageService.java
src/main/java/com/undefinedus/backend/service/KakaoTalkService.java
src/main/java/com/undefinedus/backend/service/MemberService.java
src/main/java/com/undefinedus/backend/service/MemberServiceImpl.java
src/test/java/com/undefinedus/backend/repository/MemberRepositoryTest.java
src/test/java/com/undefinedus/backend/repository/MyBookmarkRepositoryTest.java
src/test/java/com/undefinedus/backend/scheduler/KakaoTalkSenderTest.java
src/test/java/com/undefinedus/backend/service/AiServiceImplTests.java
src/test/java/com/undefinedus/backend/service/KakaoTalkServiceTest.java
src/test/resources/application.yml

- perplexity 사용 책 추천을 위해 perplexity 사용
- kakaoTalk 확인 메시지 보내기가 가능한지 확인을 위해 커밋함

feat(kakaoTalk, Ai): Ai는 GPT, perplexity 사용, kakaoTalk 확인

---

src/main/java/com/undefinedus/backend/dto/response/report/ReportResponseDTO.java
src/test/java/com/undefinedus/backend/service/DiscussionCommentServiceImplTest.java

fix(report): ReportResponseDTO 필드 업데이트

---

src/main/java/com/undefinedus/backend/controller/MyPageController.java
src/main/java/com/undefinedus/backend/dto/request/myPage/MyPageRequestDTO.java
src/main/java/com/undefinedus/backend/dto/response/myPage/MyPageResponseDTO.java
src/main/java/com/undefinedus/backend/service/MyPageService.java
src/main/java/com/undefinedus/backend/service/MyPageServiceImpl.java
src/test/java/com/undefinedus/backend/service/DiscussionServiceImplTest.java
src/test/java/com/undefinedus/backend/service/MyPageServiceImplTest.java

- 설정 페이지 접근 시 현재 정보를 출력하기 위한 유저 정보 GET 컨트롤러, 서비스, 테스트 작성
- DiscussionServiceImplTest 오류 수정

feat(myPage): 유저 정보 GET 메서드 작성 및 테스트 코드 오류 수정

---

src/main/java/com/undefinedus/backend/dto/response/myPage/MyPageResponseDTO.java
src/main/java/com/undefinedus/backend/service/MyPageServiceImpl.java

- 카카오톡 사용자 로그인 시 출력 되는 값중 socialLogin의 타입을 boolean으로 바꾸고 카카오 로그인 시 true, 일반 로그인 회원시 false로 출력이 됨.

fix(MyPage): socialLogin 정보 수정

---

src/main/java/com/undefinedus/backend/dto/response/discussion/DiscussionDetailResponseDTO.java
src/main/java/com/undefinedus/backend/repository/DiscussionParticipantRepository.java
src/main/java/com/undefinedus/backend/repository/ReportRepository.java
src/main/java/com/undefinedus/backend/service/DiscussionServiceImpl.java

- detail을 가져올때 boolean이 아닌 String 으로 변경
- joinAgree/joinDisagree 일때 반환값 명확하게 변경

fix(discussion): discussion 상세보기 할때 찬성/반대 확인 코드 업데이트

---

src/main/java/com/undefinedus/backend/dto/response/book/MyBookResponseDTO.java
src/main/java/com/undefinedus/backend/dto/response/social/MemberSocialInfoResponseDTO.java

- MemberSocialInfoResponseDTO, MyBookResponseDTO에 isPublic 필드를 추가
- 해당 회원이 소셜 접근을 허락하는지 여부, 이를 통해 프론트에서 블락처리

fix(social): 타겟 회원의 정보 확인시 isPublic 필드 추가

---

src/main/java/com/undefinedus/backend/controller/MyPageController.java
src/main/java/com/undefinedus/backend/domain/entity/Member.java
src/main/java/com/undefinedus/backend/service/MemberServiceImpl.java
src/main/java/com/undefinedus/backend/service/MyPageService.java
src/main/java/com/undefinedus/backend/service/MyPageServiceImpl.java
src/test/java/com/undefinedus/backend/service/MyPageServiceImplTest.java

- 카카오 권한 획득 시 db 의 KakaoMessageIsAgree 항목을 수정하기 위한 controller, service, set 메서드 작성

feat(myPage): 카카오 권한 업데이트 기능

---

src/main/java/com/undefinedus/backend/service/EmailService.java
src/main/java/com/undefinedus/backend/service/MyPageServiceImpl.java

- 이메일 전송시 문자 5 -> 3분으로 변경
- 카카오톡 동의와 카카오톡 문자보내는 기능 켜는 것은 별개로 판단하고 코드 수정

fix: 코드 업데이트

---

src/main/java/com/undefinedus/backend/domain/entity/DiscussionComment.java
src/main/java/com/undefinedus/backend/repository/DiscussionCommentRepository.java
src/main/java/com/undefinedus/backend/scheduler/config/QuartzConfig.java
src/main/java/com/undefinedus/backend/scheduler/job/KakaoTalkJob.java

- 답글은 베스트 댓글이 될 수 없게 수정
- kakao 메시지 보내기는 중복으로 실행되지 않게 수정

fix(comment, kakao): 베스트 댓글 출력 수정, kakao 메시지 보내기 수정

---

src/main/java/com/undefinedus/backend/dto/response/discussionComment/DiscussionCommentResponseDTO.java
src/main/java/com/undefinedus/backend/service/DiscussionCommentServiceImpl.java
src/test/java/com/undefinedus/backend/service/DiscussionCommentServiceImplTest.java

- 댓글 리스트 출력시 답글 시 부모 댓글 회원의 닉네임을 같이 출력 하게 로직 구현

fix(comment): 댓글 출력 수정

---

src/main/java/com/undefinedus/backend/config/CustomSecurityConfig.java
src/main/java/com/undefinedus/backend/controller/SocialController.java
src/main/java/com/undefinedus/backend/dto/request/ScrollRequestDTO.java
src/main/java/com/undefinedus/backend/dto/request/discussionComment/DiscussionCommentsScrollRequestDTO.java
src/main/java/com/undefinedus/backend/dto/request/discussionComment/DiscussionScrollRequestDTO.java
src/main/java/com/undefinedus/backend/scheduler/config/QuartzConfig.java
src/main/java/com/undefinedus/backend/service/AiServiceImpl.java

- 디스커션 코멘트, 소셜 팔로우 리스트의 size 100으로 변경, 나머지는 30으로 변경
- AiServiceImpl 관련 업데이트
- 쿼츠 스케쥴러의 시간 변경
- CustomSecurityConfig의 CORS 주소 추가

fix: 요청사항 변경

---

src/main/java/com/undefinedus/backend/controller/DiscussionCommentController.java
src/main/java/com/undefinedus/backend/controller/ReportController.java
src/main/java/com/undefinedus/backend/service/DiscussionCommentService.java
src/main/java/com/undefinedus/backend/service/DiscussionCommentServiceImpl.java
src/test/java/com/undefinedus/backend/service/DiscussionCommentServiceImplTest.java

- discussionCommentService.getBest3CommentByCommentLikes 진행시 체크후 isReport 값 넣어주는 코드 업데이트

fix(discussionComment): 베스트 3 토론 댓글에 로그인 사용자가 신고했는지에 대한 필드 업데이트

---

build.gradle
src/main/java/com/undefinedus/backend/controller/AladinAPIController.java
src/main/java/com/undefinedus/backend/domain/entity/AladinBook.java
src/main/java/com/undefinedus/backend/repository/DiscussionCommentRepository.java
src/main/java/com/undefinedus/backend/scheduler/config/QuartzConfig.java
src/main/java/com/undefinedus/backend/service/AiServiceImpl.java
src/main/java/com/undefinedus/backend/service/AladinBookService.java
src/main/java/com/undefinedus/backend/service/AladinBookServiceImpl.java
src/test/java/com/undefinedus/backend/service/AladinBookServiceImplTests.java

- ai에게 출력물을 받는 코드 자체가 에러 날 수 있어 에러 시 재시도 코드 구현
- 검색 리스트에서도 회원이 담은 책이라 알 수 있게 상태값 함께 출력

fix(aladinBook, ai): ai 에러 시 재시도 코드, 알라딘 검색 리스트 책 상태 값 출력 코드 구현

---

src/main/java/com/undefinedus/backend/domain/entity/DiscussionComment.java
src/main/java/com/undefinedus/backend/domain/enums/DiscussionCommentStatus.java
src/main/java/com/undefinedus/backend/dto/response/discussionComment/DiscussionCommentResponseDTO.java
src/main/java/com/undefinedus/backend/service/DiscussionCommentServiceImpl.java
src/main/java/com/undefinedus/backend/service/ReportServiceImpl.java
src/test/java/com/undefinedus/backend/repository/ReportRepositoryTest.java
src/test/java/com/undefinedus/backend/service/ReportServiceImplTest.java

- 댓글 신고 시 상태 값인 DiscussionCommentStatus를 ViewStatus로 변경

fix(comment): 댓글 상태 값 명칭 변경

---

build.gradle
src/main/java/com/undefinedus/backend/controller/MemberController.java
src/main/java/com/undefinedus/backend/dto/request/member/PasswordUpdateRequestDTO.java
src/main/java/com/undefinedus/backend/service/MemberService.java
src/main/java/com/undefinedus/backend/service/MemberServiceImpl.java

- 비밀번호 찾기 컨트롤러, 서비스 코드 업데이트
- 배포 버전 1.0.1 로 업그레이드

feat(member): 비밀번호 찾기 기능 업데이트

---

src/main/java/com/undefinedus/backend/dto/response/discussionComment/DiscussionCommentResponseDTO.java
src/main/java/com/undefinedus/backend/service/DiscussionCommentServiceImpl.java

- isLike는 로그인한 회원이 좋아요, 싫어요 누를 시 그 댓글에 눌렀는지 확인 용
- 부모 댓글이 탈퇴되면 답글에 있는 부모댓글의 닉네임도 같이 탈퇴 했음을 표시

fix(comment): 댓글 출력 시 isLike 표시, 탈퇴한 회원 표시

---

.github/workflows/deploy.yml

- 빌드 실행시 -plain.jar 제외 코드 업데이트

fix(cicd): deploy.yml 업데이트

---

src/main/java/com/undefinedus/backend/dto/response/discussion/DiscussionDetailResponseDTO.java
src/main/java/com/undefinedus/backend/service/DiscussionServiceImpl.java

- private Integer agreeCommentCount; private Integer disagreeCommentCount; 필드 추가
- 서비스에서 위의 두 값을 넣어주도록 업데이트

fix(discussion): DiscussionDetailResponseDTO 업데이트
